language: python
notifications:
  email: false
  slack: polinfo:y7iNVl10k7YTrw3EQc9NRY7H
install:
  - pip install codecov
  - pip install pytest pytest-cov
python:
  - "3.6"
script:
  - pytest --cov=./
after_success:
  - codecov -t $token_codecov