language: python
notifications:
  slack: polytechbowling:wZFQdCpaI5kyNStxsN8sI2F9
install:
  - pip install codecov
  - pip install pytest pytest-cov
python:
  - "3.6"
script:
  - pytest --cov=./
after_success:
  - codecov -t $token_codecov